# Generated by Django 6.0.2 on 2026-02-20 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('OU', 'Order Update'), ('PA', 'Product Alert'), ('RC', 'Recall'), ('SYS', 'System'), ('PRO', 'Promotion'), ('MSG', 'Message')], default='MSG', max_length=15)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(null=True)),
                ('resolved_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecallNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recall_reason', models.TextField()),
                ('Severity', models.CharField(choices=[('LOW', 'Low'), ('MED', 'Medium'), ('HI', 'High')], max_length=10)),
                ('issued_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecallNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notified_at', models.DateTimeField(auto_now_add=True)),
                ('Notified_by', models.CharField(choices=[('EML', 'Email'), ('SMS', 'SMS'), ('APP', 'App'), ('PNE', 'Phone')], default='EML', max_length=10)),
                ('acknowledged', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TraceabilityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
