# Generated by Django 6.0.2 on 2026-02-20 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('OU', 'Order Update'), ('PA', 'Product Alert'), ('RC', 'Recall'), ('SYS', 'System'), ('PRO', 'Promotion'), ('MSG', 'Message')], default='MSG', max_length=15)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(null=True)),
                ('resolved_at', models.DateTimeField(null=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_notifications', to='orders.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_notifications', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecallNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recall_reason', models.TextField()),
                ('Severity', models.CharField(choices=[('LOW', 'Low'), ('MED', 'Medium'), ('HI', 'High')], max_length=10)),
                ('issued_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(null=True)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producer_notice', to='accounts.producer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_notice', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='RecallNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notified_at', models.DateTimeField(auto_now_add=True)),
                ('Notified_by', models.CharField(choices=[('EML', 'Email'), ('SMS', 'SMS'), ('APP', 'App'), ('PNE', 'Phone')], default='EML', max_length=10)),
                ('acknowledged', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_recall', to='accounts.customer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_recall', to='orders.order')),
                ('recall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recall_recall', to='notifications.recallnotice')),
            ],
        ),
        migrations.CreateModel(
            name='TraceabilityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_tracebility', to='accounts.customer')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_tracebility', to='orders.orderitem')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producer_tracebility', to='accounts.producer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_tracebility', to='products.product')),
            ],
        ),
    ]
