# Generated by Django 6.0.1 on 2026-02-19 16:40

import django.db.models.deletion
import django_mysql.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', django_mysql.models.EnumField(choices=[('ORDER_UPDATE', 'ORDER_UPDATE'), ('PRODUCT_ALERT', 'PRODUCT_ALERT'), ('RECALL', 'RECALL'), ('SYSTEM', 'SYSTEM'), ('PROMOTION', 'PROMOTION'), ('MESSAGE', 'MESSAGE')])),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(null=True)),
                ('resolved_at', models.DateTimeField(null=True)),
                ('order_id', models.ForeignKey(db_column='order_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('product_id', models.ForeignKey(db_column='product_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecallNotice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('recall_reason', models.TextField()),
                ('severity', django_mysql.models.EnumField(choices=[('LOW', 'LOW'), ('MEDIUM', 'MEDIUM'), ('HIGH', 'HIGH')])),
                ('issued_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(null=True)),
                ('producer_id', models.ForeignKey(db_column='producer_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.producer')),
                ('product_id', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='RecallNotification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('notified_at', models.DateTimeField(auto_now_add=True)),
                ('notified_by', django_mysql.models.EnumField(choices=[('EMAIL', 'EMAIL'), ('SMS', 'SMS'), ('APP', 'APP'), ('PHONE', 'PHONE')])),
                ('acknowledged', models.BooleanField(default=False)),
                ('customer_id', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.customer')),
                ('order_id', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('recall_id', models.ForeignKey(db_column='recall_id', on_delete=django.db.models.deletion.CASCADE, to='notifications.recallnotice')),
            ],
        ),
        migrations.CreateModel(
            name='TraceabilityRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('customer_id', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.customer')),
                ('order_item_id', models.ForeignKey(db_column='order_item_id', on_delete=django.db.models.deletion.CASCADE, to='orders.orderitem')),
                ('producer_id', models.ForeignKey(db_column='producer_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.producer')),
                ('product_id', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
