# Generated by Django 6.0.1 on 2026-02-24 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recallnotice',
            old_name='Severity',
            new_name='severity',
        ),
    ]
