# Generated by Django 6.0.2 on 2026-02-20 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('notifications', '0001_initial'),
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_notifications', to='orders.order'),
        ),
        migrations.AddField(
            model_name='notification',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_notifications', to='products.product'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recallnotice',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producer_notice', to='accounts.producer'),
        ),
        migrations.AddField(
            model_name='recallnotice',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_notice', to='products.product'),
        ),
        migrations.AddField(
            model_name='recallnotification',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_recall', to='accounts.customer'),
        ),
        migrations.AddField(
            model_name='recallnotification',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_recall', to='orders.order'),
        ),
        migrations.AddField(
            model_name='recallnotification',
            name='recall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recall_recall', to='notifications.recallnotice'),
        ),
        migrations.AddField(
            model_name='traceabilityrecord',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_tracebility', to='accounts.customer'),
        ),
        migrations.AddField(
            model_name='traceabilityrecord',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_tracebility', to='orders.orderitem'),
        ),
        migrations.AddField(
            model_name='traceabilityrecord',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producer_tracebility', to='accounts.producer'),
        ),
        migrations.AddField(
            model_name='traceabilityrecord',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_tracebility', to='products.product'),
        ),
    ]
