# Generated by Django 6.0.1 on 2026-02-20 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_address_latitude_remove_address_longitude'),
        ('notifications', '0001_initial'),
        ('orders', '0004_order_unique_reference'),
        ('products', '0004_rename_mid_quantity_wholesaleprice_min_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='recallnotice',
            name='producer_id',
        ),
        migrations.RemoveField(
            model_name='recallnotice',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='recallnotification',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='recallnotification',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='recallnotification',
            name='recall_id',
        ),
        migrations.RemoveField(
            model_name='traceabilityrecord',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='traceabilityrecord',
            name='order_item_id',
        ),
        migrations.RemoveField(
            model_name='traceabilityrecord',
            name='producer_id',
        ),
        migrations.RemoveField(
            model_name='traceabilityrecord',
            name='product_id',
        ),
        migrations.AddField(
            model_name='notification',
            name='order',
            field=models.ForeignKey(db_column='order', null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
        migrations.AddField(
            model_name='notification',
            name='product',
            field=models.ForeignKey(db_column='product', null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(db_column='user', default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recallnotice',
            name='producer',
            field=models.ForeignKey(db_column='producer', default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.producer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recallnotice',
            name='product',
            field=models.ForeignKey(db_column='product', default=1, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recallnotification',
            name='customer',
            field=models.ForeignKey(db_column='customer', default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recallnotification',
            name='order',
            field=models.ForeignKey(db_column='order', default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recallnotification',
            name='recall',
            field=models.ForeignKey(db_column='recall', default=1, on_delete=django.db.models.deletion.CASCADE, to='notifications.recallnotice'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traceabilityrecord',
            name='customer',
            field=models.ForeignKey(db_column='customer', default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traceabilityrecord',
            name='order_item',
            field=models.ForeignKey(db_column='order_item', default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.orderitem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traceabilityrecord',
            name='producer',
            field=models.ForeignKey(db_column='producer', default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.producer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traceabilityrecord',
            name='product',
            field=models.ForeignKey(db_column='product', default=1, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
            preserve_default=False,
        ),
    ]
