# Generated by Django 6.0.1 on 2026-02-24 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_rename_severity_recallnotice_severity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recallnotification',
            old_name='Notified_by',
            new_name='notified_by',
        ),
    ]
