# Generated by Django 6.0.1 on 2026-03-06 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_producer_stripe_account_id'),
        ('notifications', '0003_rename_notified_by_recallnotification_notified_by'),
        ('products', '0005_remove_product_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='traceabilityrecord',
            name='guest_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='traceabilityrecord',
            name='guest_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='traceabilityrecord',
            name='guest_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='traceabilityrecord',
            name='inventory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='traceability_records', to='products.inventory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='traceabilityrecord',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='traceability_records', to='accounts.customer'),
        ),
    ]
