# Generated by Django 6.0.1 on 2026-05-04 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_traceabilityrecord_guest_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('OP', 'Order Placed'), ('OU', 'Order Update'), ('OC', 'Order Cancelled'), ('RF', 'Refund'), ('PA', 'Product Alert'), ('RC', 'Recall'), ('SYS', 'System'), ('PRO', 'Promotion'), ('MSG', 'Message')], default='MSG', max_length=15),
        ),
    ]
