# Generated by Django 6.0.1 on 2026-05-06 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('OP', 'Order Placed'), ('OU', 'Order Update'), ('OC', 'Order Cancelled'), ('RF', 'Refund'), ('PA', 'Product Alert'), ('RC', 'Recall'), ('SYS', 'System'), ('PRO', 'Promotion'), ('MSG', 'Message'), ('review_flagged', 'Review flagged'), ('admin_alert', 'Admin alert'), ('system_alert', 'System alert'), ('review_update', 'Review update')], default='MSG', max_length=15),
        ),
    ]
