# Generated by Django 6.0.2 on 2026-02-20 20:58

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('CRD', 'Card'), ('CSH', 'Cash'), ('AW', 'Account wallet'), ('VOU', 'Voucher')], max_length=20)),
                ('payment_status', models.CharField(choices=[('PEN', 'Pending'), ('SUC', 'Success'), ('FAI', 'Failed'), ('REF', 'Refunded')], default='PEN', max_length=10)),
                ('transaction_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('sandbox_mode', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='ProducerSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settlement_week', models.DateField()),
                ('total_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_commission', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('payment_reference', models.CharField(max_length=255)),
                ('payout_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('payout_status', models.CharField(choices=[('PEN', 'Pending'), ('PRO', 'Processing'), ('PAI', 'Paid'), ('FAI', 'Failed')], default='PEN', max_length=12)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='accounts.producer')),
            ],
        ),
        migrations.CreateModel(
            name='SettlementLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlement_line_items', to='orders.orderitem')),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='payments.producersettlement')),
            ],
        ),
        migrations.AddConstraint(
            model_name='producersettlement',
            constraint=models.UniqueConstraint(fields=('producer', 'settlement_week'), name='uniq_settlement_per_producer_per_week'),
        ),
    ]
