# Generated by Django 6.0.1 on 2026-03-23 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_order'),
        ('payments', '0003_payment_card_brand_payment_card_last4'),
    ]

    operations = [
    ]
