# Generated by Django 6.0.1 on 2026-05-04 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_orderitem_cancellation_reason_orderitem_cancelled_at_and_more'),
        ('payments', '0005_alter_payment_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('PEN', 'Pending'), ('SUC', 'Success'), ('FAI', 'Failed'), ('PREF', 'Partially refunded'), ('REF', 'Refunded')], default='PEN', max_length=10),
        ),
        migrations.CreateModel(
            name='PaymentRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stripe_refund_id', models.CharField(blank=True, default='', max_length=255)),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PEN', 'Pending'), ('SUC', 'Succeeded'), ('FAI', 'Failed')], default='PEN', max_length=10)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_refunds', to='orders.order')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_refunds', to='orders.orderitem')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='payments.payment')),
            ],
        ),
    ]
