# Generated by Django 6.0.1 on 2026-02-19 16:40

import django.core.validators
import django.db.models.deletion
import django_mysql.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('anonymous', models.BooleanField()),
                ('status', django_mysql.models.EnumField(choices=[('PUBLISHED', 'PUBLISHED'), ('HIDDEN', 'HIDDEN'), ('FLAGGED', 'FLAGGED'), ('REMOVED', 'REMOVED')])),
                ('moderated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer_id', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.customer')),
                ('moderated_by_admin_id', models.ForeignKey(db_column='admin_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.admin')),
                ('order_id', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('product_id', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewResponse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('response_text', models.TextField(blank=True)),
                ('status', django_mysql.models.EnumField(choices=[('PUBLISHED', 'PUBLISHED'), ('HIDDEN', 'HIDDEN'), ('FLAGGED', 'FLAGGED'), ('REMOVED', 'REMOVED')])),
                ('moderated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('producer_id', models.ForeignKey(db_column='producer_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.producer')),
                ('review_id', models.ForeignKey(db_column='review_id', on_delete=django.db.models.deletion.CASCADE, to='reviews.review')),
            ],
        ),
    ]
