# Generated by Django 6.0.2 on 2026-02-20 22:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('anonymous', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('PUB', 'Published'), ('HID', 'Hidden'), ('FLG', 'Flagged'), ('RMV', 'Removed')], default='PUB', max_length=10)),
                ('moderated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_reviews', to='accounts.customer')),
                ('moderated_by_admin_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_reviews', to='accounts.admin')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_reviews', to='orders.order')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_reviews', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PUB', 'Published'), ('HID', 'Hidden'), ('FLG', 'Flagged'), ('RMV', 'Removed')], default='PUB', max_length=10)),
                ('moderated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('moderated_by_admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderated_by_admin_reviews', to='accounts.admin')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producer_reviews', to='accounts.producer')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_reviews', to='reviews.review')),
            ],
        ),
    ]
