# Generated by Django 6.0.1 on 2026-02-19 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewresponse',
            name='moderated_by_admin_id',
            field=models.ForeignKey(db_column='moderated_by_admin_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.admin'),
        ),
    ]
