# Generated by Django 6.0.1 on 2026-04-08 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_role'),
        ('reviews', '0002_review_order_item_delete_reviewresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='moderated_by_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_reviews', to='accounts.admin'),
        ),
    ]
