# Generated by Django 6.0.1 on 2026-02-20 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_address_latitude_remove_address_longitude'),
        ('orders', '0004_order_unique_reference'),
        ('products', '0005_remove_product_category_id_and_more'),
        ('reviews', '0002_reviewresponse_moderated_by_admin_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='review',
            name='moderated_by_admin_id',
        ),
        migrations.RemoveField(
            model_name='review',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='review',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='reviewresponse',
            name='moderated_by_admin_id',
        ),
        migrations.RemoveField(
            model_name='reviewresponse',
            name='producer_id',
        ),
        migrations.RemoveField(
            model_name='reviewresponse',
            name='review_id',
        ),
        migrations.AddField(
            model_name='review',
            name='customer',
            field=models.ForeignKey(db_column='customer', default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='moderated_by_admin',
            field=models.ForeignKey(db_column='admin', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.admin'),
        ),
        migrations.AddField(
            model_name='review',
            name='order',
            field=models.ForeignKey(db_column='order', default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='product',
            field=models.ForeignKey(db_column='product', default=1, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviewresponse',
            name='moderated_by_admin',
            field=models.ForeignKey(db_column='moderated_by_admin', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.admin'),
        ),
        migrations.AddField(
            model_name='reviewresponse',
            name='producer',
            field=models.ForeignKey(db_column='producer', default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.producer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviewresponse',
            name='review',
            field=models.ForeignKey(db_column='review', default=1, on_delete=django.db.models.deletion.CASCADE, to='reviews.review'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reviewresponse',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
