# Generated by Django 6.0.1 on 2026-04-08 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_role'),
        ('orders', '0011_alter_order_status_and_more'),
        ('products', '0013_remove_inventoryupdatehistory_status_and_more'),
        ('reviews', '0003_alter_review_moderated_by_admin'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('customer', 'product'), name='unique_review_per_customer_per_product'),
        ),
    ]
