# Generated by Django 6.0.1 on 2026-04-23 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_role'),
        ('orders', '0011_alter_order_status_and_more'),
        ('products', '0013_remove_inventoryupdatehistory_status_and_more'),
        ('reviews', '0004_review_unique_review_per_customer_per_product'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='unique_review_per_customer_per_product',
        ),
        migrations.AlterField(
            model_name='review',
            name='moderated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'RMV'), _negated=True), fields=('customer', 'product'), name='unique_active_review_per_customer_per_product'),
        ),
    ]
