# Generated by Django 6.0.1 on 2026-04-29 00:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_remove_review_unique_review_per_customer_per_product_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='moderation_notes',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='ReviewProducerResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('status', models.CharField(choices=[('PUB', 'Published'), ('FLG', 'Flagged'), ('RMV', 'Removed')], default='PUB', max_length=3)),
                ('moderated_at', models.DateTimeField(blank=True, null=True)),
                ('moderation_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producer_review_responses', to=settings.AUTH_USER_MODEL)),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='producer_response', to='reviews.review')),
            ],
            options={
                'verbose_name': 'Producer review response',
                'verbose_name_plural': 'Producer review responses',
                'ordering': ['-updated_at', '-id'],
            },
        ),
    ]
