# Generated by Django 6.0.2 on 2026-02-20 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_recipes', to='products.product'),
        ),
        migrations.AddField(
            model_name='recipeproduct',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_products', to='community.recipe'),
        ),
        migrations.AlterUniqueTogether(
            name='favouriterecipe',
            unique_together={('user', 'recipe')},
        ),
    ]
