# Generated by Django 6.0.1 on 2026-04-28 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmstory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='farm_stories/'),
        ),
    ]
