# Generated by Django 6.0.1 on 2026-05-06 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_alter_farmstory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='status',
            field=models.CharField(choices=[('PUB', 'Published'), ('HID', 'Hidden'), ('FLG', 'Flagged'), ('RMV', 'Removed')], default='PUB', max_length=20),
        ),
    ]
