# Generated by Django 6.0.1 on 2026-02-27 12:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_or_collection',
        ),
        migrations.AddField(
            model_name='order',
            name='total_vat',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4),
        ),
        migrations.AddField(
            model_name='producerordersummary',
            name='address_line1',
            field=models.CharField(default='42 Ranch Road', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producerordersummary',
            name='address_line2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='producerordersummary',
            name='city',
            field=models.CharField(default='Bristol', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producerordersummary',
            name='delivery_or_collection',
            field=models.CharField(choices=[('DEL', 'Delivery'), ('COL', 'Collection')], default='DEL', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producerordersummary',
            name='delivery_time_slot',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producerordersummary',
            name='postcode',
            field=models.CharField(default='BS16 2AX', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producerordersummary',
            name='vat_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='producerordersummary',
            name='delivery_date',
            field=models.DateField(),
        ),
    ]
