# Generated by Django 6.0.1 on 2026-02-19 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='commision_amount',
            new_name='commission_amount',
        ),
    ]
