# Generated by Django 6.0.1 on 2026-02-26 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_total_vat_orderitem_vat_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producerordersummary',
            name='address_line1',
            field=models.CharField(default='14 Farm Road', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producerordersummary',
            name='address_line2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='producerordersummary',
            name='city',
            field=models.CharField(default='Bristol', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producerordersummary',
            name='delivery_or_collection',
            field=models.CharField(choices=[('DEL', 'Delivery'), ('COL', 'Collection')], default='DEL', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producerordersummary',
            name='delivery_time_slot',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producerordersummary',
            name='postcode',
            field=models.CharField(default='BS16 2AX', max_length=20),
            preserve_default=False,
        ),
    ]
