# Generated by Django 6.0.1 on 2026-02-19 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('orders', '0002_rename_commision_amount_orderitem_commission_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.ForeignKey(default=14, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='accounts.address'),
            preserve_default=False,
        ),
    ]
