# Generated by Django 6.0.1 on 2026-02-26 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_producerordersummary_address_line1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_or_collection',
        ),
    ]
