# Generated by Django 6.0.1 on 2026-02-20 13:30

import shortuuidfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_delivery_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='unique_reference',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, unique=True),
        ),
    ]
