# Generated by Django 6.0.1 on 2026-02-26 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_delivery_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producerordersummary',
            name='delivery_date',
            field=models.DateField(),
        ),
    ]
