# Generated by Django 6.0.1 on 2026-03-06 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_billing_address_order_guest_email_and_more'),
        ('products', '0005_remove_product_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='inventory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='products.inventory'),
            preserve_default=False,
        ),
    ]
