# Generated by Django 6.0.1 on 2026-03-12 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orderitem_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producerorderstatushistory',
            name='new_status',
            field=models.CharField(choices=[('PEN', 'Pending'), ('PRE', 'Preparing'), ('PAC', 'Packaged'), ('SHP', 'Shipped'), ('CAN', 'Cancelled'), ('COM', 'Completed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='producerorderstatushistory',
            name='old_status',
            field=models.CharField(choices=[('PEN', 'Pending'), ('PRE', 'Preparing'), ('PAC', 'Packaged'), ('SHP', 'Shipped'), ('CAN', 'Cancelled'), ('COM', 'Completed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='producerordersummary',
            name='status',
            field=models.CharField(choices=[('PEN', 'Pending'), ('PRE', 'Preparing'), ('PAC', 'Packaged'), ('SHP', 'Shipped'), ('CAN', 'Cancelled'), ('COM', 'Completed')], default='PEN', max_length=20),
        ),
    ]
