# Generated by Django 6.0.1 on 2026-03-26 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_producerorderstatushistory_new_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringorder',
            name='delivery_day',
            field=models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], help_text='The day of the week the initial order is delivered on.', max_length=3),
        ),
        migrations.AlterField(
            model_name='recurringorder',
            name='recurrence_day',
            field=models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], default='MON', help_text='The day of the week the recurring order repeats on.', max_length=3),
        ),
        migrations.AlterField(
            model_name='recurringorder',
            name='recurrence_pattern',
            field=models.CharField(choices=[('WEEKLY', 'Weekly'), ('FORTNIGHTLY', 'Fortnightly')], max_length=15),
        ),
        migrations.AlterField(
            model_name='recurringorder',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=10),
        ),
    ]
