# Generated by Django 6.0.1 on 2026-03-26 12:19

from django.db import migrations


def migrate_old_choice_values(apps, schema_editor):
    """Convert old short-code choice values to full-word values."""
    RecurringOrder = apps.get_model('orders', 'RecurringOrder')

    # Migrate recurrence_pattern
    RecurringOrder.objects.filter(recurrence_pattern='WK').update(recurrence_pattern='WEEKLY')
    RecurringOrder.objects.filter(recurrence_pattern='FN').update(recurrence_pattern='FORTNIGHTLY')

    # Migrate status
    RecurringOrder.objects.filter(status='ACT').update(status='ACTIVE')
    RecurringOrder.objects.filter(status='PS').update(status='PAUSED')
    RecurringOrder.objects.filter(status='CAN').update(status='CANCELLED')


def reverse_migrate(apps, schema_editor):
    """Reverse: convert full-word values back to short codes."""
    RecurringOrder = apps.get_model('orders', 'RecurringOrder')

    RecurringOrder.objects.filter(recurrence_pattern='WEEKLY').update(recurrence_pattern='WK')
    RecurringOrder.objects.filter(recurrence_pattern='FORTNIGHTLY').update(recurrence_pattern='FN')

    RecurringOrder.objects.filter(status='ACTIVE').update(status='ACT')
    RecurringOrder.objects.filter(status='PAUSED').update(status='PS')
    RecurringOrder.objects.filter(status='CANCELLED').update(status='CAN')


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_recurringorder_choices'),
    ]

    operations = [
        migrations.RunPython(migrate_old_choice_values, reverse_migrate),
    ]
