# Generated by Django 6.0.1 on 2026-04-23 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_role'),
        ('orders', '0010_migrate_old_choice_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PEN', 'Pending'), ('IP', 'In progress'), ('OFD', 'Packaged'), ('RFC', 'Ready for collection'), ('CMP', 'Completed'), ('CAN', 'Cancelled')], default='PEN', max_length=30),
        ),
        migrations.AlterField(
            model_name='recurringorder',
            name='delivery_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_orders', to='accounts.address'),
        ),
    ]
