# Generated by Django 6.0.1 on 2026-05-04 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_orderitem_cancellation_reason_orderitem_cancelled_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producerorderstatushistory',
            name='new_status',
            field=models.CharField(choices=[('PEN', 'Pending'), ('PRE', 'Preparing'), ('PAC', 'Packaged'), ('RFC', 'Ready for collection'), ('SHP', 'Shipped'), ('CAN', 'Cancelled'), ('COM', 'Completed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='producerorderstatushistory',
            name='old_status',
            field=models.CharField(choices=[('PEN', 'Pending'), ('PRE', 'Preparing'), ('PAC', 'Packaged'), ('RFC', 'Ready for collection'), ('SHP', 'Shipped'), ('CAN', 'Cancelled'), ('COM', 'Completed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='producerordersummary',
            name='status',
            field=models.CharField(choices=[('PEN', 'Pending'), ('PRE', 'Preparing'), ('PAC', 'Packaged'), ('RFC', 'Ready for collection'), ('SHP', 'Shipped'), ('CAN', 'Cancelled'), ('COM', 'Completed')], default='PEN', max_length=20),
        ),
    ]
