# Generated by Django 6.0.1 on 2026-05-06 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_alter_producerorderstatushistory_new_status_and_more'),
        ('payments', '0006_alter_payment_payment_status_paymentrefund'),
    ]

    operations = [
        migrations.AddField(
            model_name='producerordersummary',
            name='settlement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='summaries', to='payments.producersettlement'),
        ),
    ]
