# Generated by Django 6.0.1 on 2026-02-23 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DistanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producer_postcode', models.CharField(max_length=20)),
                ('customer_postcode', models.CharField(max_length=20)),
                ('distance_miles', models.DecimalField(decimal_places=2, max_digits=10)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdminPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('category', models.CharField(choices=[('AN', 'Announcement'), ('UP', 'Update'), ('MTN', 'Maintenance'), ('POL', 'Policy'), ('PRO', 'Promotion')], max_length=20)),
                ('image', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_post', to='accounts.admin')),
            ],
        ),
        migrations.CreateModel(
            name='ModerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('REC', 'Recipe'), ('FS', 'Farm Story'), ('PRO', 'Product'), ('RN', 'Recall Notice'), ('REV', 'Review'), ('OTH', 'Other')], max_length=20)),
                ('content_id', models.IntegerField()),
                ('action', models.CharField(choices=[('FLG', 'Flagged'), ('APP', 'Approved'), ('REJ', 'Rejected'), ('REM', 'Removed'), ('RES', 'Restored')], max_length=15)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_action', to='accounts.admin')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producer_action', to='accounts.producer')),
            ],
        ),
        migrations.CreateModel(
            name='SecurityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('LS', 'Login Success'), ('LF', 'Login Failure'), ('PR', 'Password Reset'), ('AL', 'Account Locked'), ('TR', 'Token Refresh'), ('SA', 'Suspicious Activity'), ('PD', 'Permission Denied'), ('LO', 'Logout')], default='AL', max_length=20)),
                ('ip_address', models.CharField(max_length=45)),
                ('user_agent', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_security', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
