# Generated by Django 6.0.1 on 2026-02-19 16:40

import django.db.models.deletion
import django_mysql.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DistanceRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('producer_postcode', models.CharField(max_length=20)),
                ('customer_postcode', models.CharField(max_length=20)),
                ('distance_miles', models.DecimalField(decimal_places=2, max_digits=10)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdminPost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('category', django_mysql.models.EnumField(choices=[('ANNOUNCEMENT', 'ANNOUNCEMENT'), ('UPDATE', 'UPDATE'), ('MAINTENANCE', 'MAINTENANCE'), ('POLICY', 'POLICY'), ('PROMOTION', 'PROMOTION')])),
                ('image', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_id', models.ForeignKey(db_column='admin_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.admin')),
            ],
        ),
        migrations.CreateModel(
            name='ModerationLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content_type', django_mysql.models.EnumField(choices=[('RECIPE', 'RECIPE'), ('FARM_STORY', 'FARM_STORY'), ('PRODUCT', 'PRODUCT'), ('RECALL_NOTICE', 'RECALL_NOTICE'), ('REVIEW', 'REVIEW'), ('OTHER', 'OTHER')])),
                ('content_id', models.IntegerField()),
                ('action', django_mysql.models.EnumField(choices=[('FLAGGED', 'FLAGGED'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED'), ('REMOVED', 'REMOVED'), ('RESTORED', 'RESTORED')])),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_id', models.ForeignKey(db_column='admin_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.admin')),
                ('producer_id', models.ForeignKey(db_column='producer_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.producer')),
            ],
        ),
        migrations.CreateModel(
            name='SecurityLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_type', django_mysql.models.EnumField(choices=[('LOGIN_SUCCESS', 'LOGIN_SUCCESS'), ('LOGIN_FAILURE', 'LOGIN_FAILURE'), ('PASSWORD_RESET', 'PASSWORD_RESET'), ('ACCOUNT_LOCKED', 'ACCOUNT_LOCKED'), ('TOKEN_REFRESH', 'TOKEN_REFRESH'), ('SUSPICIOUS_ACTIVITY', 'SUSPICIOUS_ACTIVITY'), ('PERMISSION_DENIED', 'PERMISSION_DENIED'), ('LOGOUT', 'LOGOUT')])),
                ('ip_address', models.CharField(max_length=45)),
                ('user_agent', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(null=True)),
                ('user_id', models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
