# Generated by Django 6.0.1 on 2026-02-20 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_address_latitude_remove_address_longitude'),
        ('admin_records', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='moderationlog',
            old_name='content_id',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='adminpost',
            name='admin_id',
        ),
        migrations.RemoveField(
            model_name='moderationlog',
            name='admin_id',
        ),
        migrations.RemoveField(
            model_name='moderationlog',
            name='producer_id',
        ),
        migrations.RemoveField(
            model_name='securitylog',
            name='user_id',
        ),
        migrations.AddField(
            model_name='adminpost',
            name='admin',
            field=models.ForeignKey(db_column='admin', default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.admin'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moderationlog',
            name='admin',
            field=models.ForeignKey(db_column='admin', default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.admin'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moderationlog',
            name='producer',
            field=models.ForeignKey(db_column='producer', default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.producer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='securitylog',
            name='user',
            field=models.ForeignKey(db_column='user', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='adminpost',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='moderationlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='securitylog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
