# Generated by Django 6.0.1 on 2026-02-24 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_records', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminpost',
            old_name='admin_id',
            new_name='admin',
        ),
    ]
