# Generated by Django 6.0.1 on 2026-02-24 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_records', '0002_rename_admin_id_adminpost_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moderationlog',
            old_name='content_id',
            new_name='content',
        ),
    ]
