# Generated by Django 6.0.1 on 2026-02-27 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_remove_cart_cart_user_xor_guest_cart_session_key_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ['created_at', 'id']},
        ),
    ]
