# Generated by Django 6.0.1 on 2026-03-06 10:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_alter_cartitem_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cart',
            name='cart_status_updated_idx',
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['status', '-updated_at'], name='cart_status_updated_idx'),
        ),
    ]
