# Generated by Django 6.0.1 on 2026-03-06 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_alter_cartitem_options'),
        ('products', '0005_remove_product_expiry_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cartitem',
            name='uniq_cart_product',
        ),
        migrations.RemoveIndex(
            model_name='cart',
            name='cart_status_updated_idx',
        ),
        migrations.RemoveIndex(
            model_name='cartitem',
            name='cartitem_cart_product_idx',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='inventory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='products.inventory'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['status', '-updated_at'], name='cart_status_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['cart', 'inventory'], name='cartitem_cart_inventory_idx'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('cart', 'inventory'), name='uniq_cart_item'),
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
    ]
