# Generated by Django 6.0.1 on 2026-03-11 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_remove_cart_cart_status_updated_idx_and_more'),
        ('carts', '0004_remove_cartitem_uniq_cart_product_and_more'),
    ]

    operations = [
    ]
