# Generated by Django 6.0.1 on 2026-04-30 02:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0014_product_low_stock_email_sent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, default='', help_text='Supports anonymous browsing before login.', max_length=40)),
                ('event_type', models.CharField(choices=[('view', 'View'), ('addtocart', 'Add to cart'), ('transaction', 'Transaction')], default='view', max_length=20)),
                ('source', models.CharField(choices=[('web', 'Web'), ('synthetic', 'Synthetic demo data'), ('order_history', 'Order history')], default='web', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_interactions', to='products.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='ai_recommen_user_id_108012_idx'), models.Index(fields=['session_key', '-created_at'], name='ai_recommen_session_3eb57d_idx'), models.Index(fields=['product', 'event_type'], name='ai_recommen_product_9e93ae_idx'), models.Index(fields=['event_type', '-created_at'], name='ai_recommen_event_t_421c3c_idx')],
            },
        ),
    ]
