# Generated by Django 6.0.1 on 2026-05-06 20:36

import django.core.files.storage
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classifiermodel',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location=pathlib.PurePosixPath('/code/media')), upload_to='classifier_models/'),
        ),
    ]
