# Generated by Django 6.0.1 on 2026-02-23 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('PRODUCER', 'Producer'), ('COMMUNITY_GROUP', 'Community Group'), ('RESTAURANT', 'Restaurant'), ('ADMIN', 'Admin')], max_length=20),
        ),
    ]
