# Generated by Django 6.0.2 on 2026-02-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producer',
            name='payout_method',
            field=models.CharField(choices=[('BT', 'Bank Transfer'), ('PP', 'Pay Pal'), ('CHQ', 'Cheque')], max_length=20),
        ),
    ]
