# Generated by Django 6.0.2 on 2026-02-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_producer_payout_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='cheque_payee_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='producer',
            name='cheque_postal_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
