# Generated by Django 6.0.1 on 2026-03-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_address_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='stripe_account_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
