<<<<<<< HEAD
# Generated by Django 6.0.1 on 2026-04-09 14:07
=======
# Generated by Django 6.0.1 on 2026-04-07 15:19
>>>>>>> 17818930c09e15f71cf6bc24534c989fdf8cee67

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_deactivated_at_user_deactivated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('PRODUCER', 'Producer'), ('COMMUNITY_GROUP', 'Community Group'), ('BUSINESS', 'Business'), ('ADMIN', 'Admin')], max_length=20),
        ),
    ]
