# Generated by Django 6.0.1 on 2026-05-06 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producer',
            name='payout_method',
            field=models.CharField(choices=[('BT', 'Bank Transfer'), ('PP', 'Pay Pal'), ('CHQ', 'Cheque'), ('STP', 'Stripe Payouts')], max_length=20),
        ),
    ]
