# Generated by Django 6.0.1 on 2026-05-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_producer_payout_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producer',
            name='cheque_postal_address',
        ),
        migrations.AddField(
            model_name='producer',
            name='cheque_address_line1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='producer',
            name='cheque_address_line2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='producer',
            name='cheque_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producer',
            name='cheque_postcode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
