# Generated by Django 6.0.1 on 2026-05-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_producer_cheque_postal_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producer',
            name='cheque_address_line1',
        ),
        migrations.RemoveField(
            model_name='producer',
            name='cheque_address_line2',
        ),
        migrations.RemoveField(
            model_name='producer',
            name='cheque_city',
        ),
        migrations.RemoveField(
            model_name='producer',
            name='cheque_postcode',
        ),
        migrations.AddField(
            model_name='producer',
            name='cheque_postal_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
