# Generated by Django 6.0.1 on 2026-05-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_producer_cheque_address_line1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producer',
            name='payout_method',
            field=models.CharField(choices=[('BT', 'Bank Transfer'), ('PP', 'Pay Pal'), ('CHQ', 'Cheque')], max_length=20),
        ),
    ]
