# Generated by Django 6.0.1 on 2026-02-19 16:40

import django.db.models.deletion
import django_mysql.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('vat', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', django_mysql.models.EnumField(choices=[('KG', 'KG'), ('G', 'G'), ('L', 'L'), ('ML', 'ML'), ('EACH', 'EACH'), ('PACK', 'PACK'), ('BUNCH', 'BUNCH'), ('BOX', 'BOX')])),
                ('image', models.CharField(max_length=255)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('low_stock_threshold', models.IntegerField(default=0)),
                ('harvest_date', models.DateTimeField(auto_now_add=True)),
                ('farm_origin', models.CharField(max_length=150)),
                ('organic_certification_status', django_mysql.models.EnumField(choices=[('CERTIFIED', 'CERTIFIED'), ('NOT_CERTIFIED', 'NOT_CERTIFIED')])),
                ('storage_guidance', models.TextField(null=True)),
                ('expiry_date', models.DateTimeField(auto_now_add=True)),
                ('expiry_type', django_mysql.models.EnumField(choices=[('BEST_BEFORE', 'BEST_BEFORE'), ('USE_BY', 'USE_BY')])),
                ('availability_start', models.DateTimeField(auto_now_add=True)),
                ('availability_end', models.DateTimeField(auto_now_add=True)),
                ('availability_status', django_mysql.models.EnumField(choices=[('AVAILABLE', 'AVAILABLE'), ('OUT_OF_STOCK', 'OUT_OF_STOCK'), ('DISCONTINUED', 'DISCONTINUED')])),
                ('surplus_status', django_mysql.models.EnumField(choices=[('SURPLUS_ACTIVE', 'SURPLUS_ACTIVE'), ('SURPLUS_EXPIRED', 'SURPLUS_EXPIRED')])),
                ('surplus_discount_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('surplus_expiry', models.DateTimeField(auto_now_add=True, null=True)),
                ('surplus_note', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('status', django_mysql.models.EnumField(choices=[('HIDDEN', 'HIDDEN'), ('FLAGGED', 'FLAGGED'), ('REMOVED', 'REMOVED')])),
                ('moderated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('category_id', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, to='products.category')),
                ('moderated_by_admin_id', models.ForeignKey(db_column='admin_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.admin')),
                ('producer_id', models.ForeignKey(db_column='producer_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.producer')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAllergen',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('allergen_id', models.ForeignKey(db_column='allergen_id', on_delete=django.db.models.deletion.CASCADE, to='products.allergen')),
                ('product_id', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductUpdateHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('field_changed', models.CharField(max_length=100)),
                ('old_value', models.TextField()),
                ('new_value', models.TextField()),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('product_id', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SurplusProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(auto_now_add=True)),
                ('product_id', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='WholesalePrice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mid_quantity', models.IntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_id', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
