# Generated by Django 6.0.1 on 2026-02-23 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('vat', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(choices=[('KG', 'Kilogram'), ('G', 'Gram'), ('L', 'Liter'), ('ML', 'Milliliter'), ('EA', 'Each'), ('PK', 'Pack'), ('BN', 'Bunch'), ('BX', 'Box')], default='EA', max_length=5)),
                ('image', models.CharField(max_length=255)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('low_stock_threshold', models.IntegerField(default=0)),
                ('harvest_date', models.DateTimeField(auto_now_add=True)),
                ('farm_origin', models.CharField(max_length=150)),
                ('organic_certification_status', models.CharField(choices=[('CERTIFIED', 'Certified Organic'), ('NOT_CERTIFIED', 'Not Certified')], default='NOT_CERTIFIED', max_length=15)),
                ('storage_guidance', models.TextField(null=True)),
                ('expiry_date', models.DateTimeField()),
                ('expiry_type', models.CharField(choices=[('BB', 'Best Before'), ('UB', 'USE BY')], default='BB', max_length=10)),
                ('availability_start', models.DateTimeField(auto_now_add=True)),
                ('availability_end', models.DateTimeField(auto_now_add=True)),
                ('availability_status', models.CharField(choices=[('AV', 'Available'), ('OOS', 'Out of Stock'), ('DIS', 'Discontinued')], default='OOS', max_length=10)),
                ('surplus_status', models.CharField(choices=[('NN', 'None'), ('SA', 'Surplus Active'), ('SE', 'Surplus Expired')], default='NN', max_length=15)),
                ('surplus_discount_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('surplus_expiry', models.DateTimeField(auto_now_add=True, null=True)),
                ('surplus_note', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PUB', 'Published'), ('HID', 'Hidden'), ('FLG', 'Flagged'), ('RMV', 'Removed')], default='PUB', max_length=10)),
                ('moderated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_products', to='products.category')),
                ('moderated_by_admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_products', to='accounts.admin')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producer_products', to='accounts.producer')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAllergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergen_products', to='products.allergen')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_allergen', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductUpdateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_changed', models.CharField(max_length=100)),
                ('old_value', models.TextField()),
                ('new_value', models.TextField()),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_history', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WholesalePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_quantity', models.IntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_wholesale', to='products.product')),
            ],
        ),
    ]
