# Generated by Django 6.0.1 on 2026-02-19 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SurplusProduct',
        ),
    ]
