# Generated by Django 6.0.1 on 2026-02-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='expiry_type',
            field=models.CharField(choices=[('BB', 'BEST BEFORE'), ('UB', 'USE BY')], default='BB', max_length=11),
        ),
    ]
