# Generated by Django 6.0.2 on 2026-02-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_expiry_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='food_groups',
            field=models.CharField(choices=[('MT', 'Meat'), ('DAE', 'Dairy and Eggs'), ('FR', 'Fruit'), ('VEG', 'Vegetables'), ('SEA', 'Seasonal')], default='SEA', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='harvest_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products/'),
        ),
    ]
