# Generated by Django 6.0.1 on 2026-02-19 20:17

import django_mysql.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_delete_surplusproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=django_mysql.models.EnumField(choices=[('PUBLISHED', 'PUBLISHED'), ('HIDDEN', 'HIDDEN'), ('FLAGGED', 'FLAGGED'), ('REMOVED', 'REMOVED')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='surplus_status',
            field=django_mysql.models.EnumField(choices=[('NONE', 'NONE'), ('SURPLUS_ACTIVE', 'SURPLUS_ACTIVE'), ('SURPLUS_EXPIRED', 'SURPLUS_EXPIRED')]),
        ),
    ]
