# Generated by Django 6.0.1 on 2026-02-19 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_status_alter_product_surplus_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wholesaleprice',
            old_name='mid_quantity',
            new_name='min_quantity',
        ),
    ]
