# Generated by Django 6.0.1 on 2026-03-04 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_food_groups_alter_product_harvest_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergen',
            name='name',
            field=models.CharField(choices=[('NUT', 'Tree Nuts'), ('SEA', 'Sesame'), ('PEA', 'Peanuts'), ('SOY', 'Soybeans'), ('MUS', 'Mustard'), ('FSH', 'Fish'), ('MOL', 'Molluscs'), ('CRU', 'Crustaceans'), ('CEL', 'Celery'), ('GLU', 'Gluten'), ('SUL', 'Sulphur Dioxide'), ('LUP', 'Lupin'), ('EGG', 'Egg'), ('MLK', 'Milk'), ('NON', 'None')], default='NON', max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/img/'),
        ),
    ]
