# Generated by Django 6.0.1 on 2026-02-20 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_address_latitude_remove_address_longitude'),
        ('products', '0004_rename_mid_quantity_wholesaleprice_min_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='moderated_by_admin_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='producer_id',
        ),
        migrations.RemoveField(
            model_name='productallergen',
            name='allergen_id',
        ),
        migrations.RemoveField(
            model_name='productallergen',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='productupdatehistory',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='productupdatehistory',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='wholesaleprice',
            name='product_id',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(db_column='category', default=1, on_delete=django.db.models.deletion.CASCADE, to='products.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='moderated_by_admin',
            field=models.ForeignKey(db_column='admin', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.admin'),
        ),
        migrations.AddField(
            model_name='product',
            name='producer',
            field=models.ForeignKey(db_column='producer', default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.producer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productallergen',
            name='allergen',
            field=models.ForeignKey(db_column='allergen', default=1, on_delete=django.db.models.deletion.CASCADE, to='products.allergen'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productallergen',
            name='product',
            field=models.ForeignKey(db_column='product', default=1, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productupdatehistory',
            name='product',
            field=models.ForeignKey(db_column='product', default=1, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productupdatehistory',
            name='user',
            field=models.ForeignKey(db_column='user', default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wholesaleprice',
            name='product',
            field=models.ForeignKey(db_column='product', default=1, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
            preserve_default=False,
        ),
    ]
