# Generated by Django 6.0.1 on 2026-03-06 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_allergen_name_alter_product_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='expiry_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='harvest_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock_quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='surplus_discount_percentage',
        ),
        migrations.RemoveField(
            model_name='product',
            name='surplus_expiry',
        ),
        migrations.RemoveField(
            model_name='product',
            name='surplus_note',
        ),
        migrations.RemoveField(
            model_name='product',
            name='surplus_status',
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_quantity', models.IntegerField()),
                ('remaining_quantity', models.IntegerField()),
                ('harvest_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('expiry_type', models.CharField(choices=[('BB', 'Best Before'), ('UB', 'Use By')], default='BB', max_length=11)),
                ('surplus_status', models.CharField(choices=[('NN', 'None'), ('SA', 'Surplus Active'), ('SE', 'Surplus Expired')], default='NN', max_length=15)),
                ('surplus_discount_percentage', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('surplus_expiry', models.DateTimeField(null=True)),
                ('surplus_note', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_batches', to='products.product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_inventory', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
