# Generated by Django 6.0.1 on 2026-03-09 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_allergen_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergen',
            name='name',
            field=models.CharField(choices=[('TREENUTS', 'Tree Nuts'), ('SESAME', 'Sesame'), ('PEANUTS', 'Peanuts'), ('SOYBEANS', 'Soybeans'), ('MUSTARD', 'Mustard'), ('FISH', 'Fish'), ('MOLLUSCS', 'Molluscs'), ('CRUSTACEANS', 'Crustaceans'), ('CELERY', 'Celery'), ('GLUTEN', 'Gluten'), ('SULPHUR DIOXIED', 'Sulphur Dioxide'), ('LUPIN', 'Lupin'), ('EGG', 'Egg'), ('MILK', 'Milk'), ('NONE', 'None')], default='NONE', max_length=20, unique=True),
        ),
    ]
