# Generated by Django 6.0.1 on 2026-03-19 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_inventoryupdatehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryupdatehistory',
            name='ended_reason',
            field=models.CharField(choices=[('cancelled', 'Cancelled'), ('expired', 'Expired')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='inventoryupdatehistory',
            name='event_type',
            field=models.CharField(choices=[('field_change', 'Field Change'), ('reduction_started', 'Reduction Started'), ('reduction_ended', 'Reduction Ended')], default='field_change', max_length=20),
        ),
        migrations.AddField(
            model_name='inventoryupdatehistory',
            name='snapshot_discount',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='inventoryupdatehistory',
            name='snapshot_expiry',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='inventoryupdatehistory',
            name='snapshot_note',
            field=models.TextField(null=True),
        ),
    ]
