# Generated by Django 6.0.1 on 2026-03-20 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_inventoryupdatehistory_ended_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='surplus_discount_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryupdatehistory',
            name='snapshot_discount',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
