# Generated by Django 6.0.1 on 2026-03-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_producttype_product_product_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryupdatehistory',
            name='status',
            field=models.CharField(choices=[('ACT', 'Active'), ('DEL', 'Deleted')], default='ACT', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('PUB', 'Published'), ('HID', 'Hidden'), ('FLG', 'Flagged'), ('RMV', 'Removed'), ('PND', 'Pending Approval')], default='PND', max_length=10),
        ),
    ]
