# Generated by Django 6.0.1 on 2026-03-26 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_inventoryupdatehistory_status_alter_product_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryupdatehistory',
            name='status',
        ),
        migrations.AddField(
            model_name='inventory',
            name='status',
            field=models.CharField(choices=[('ACT', 'Active'), ('DEL', 'Deleted')], default='ACT', max_length=20),
        ),
    ]
