# Generated by Django 6.0.1 on 2026-04-23 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_remove_inventoryupdatehistory_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='low_stock_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
