# Generated by Django 6.0.1 on 2026-05-01 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_product_low_stock_email_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='status',
            field=models.CharField(choices=[('ACT', 'Active'), ('EXP', 'Expired'), ('DEL', 'Deleted')], default='ACT', max_length=20),
        ),
    ]
