# Generated by Django 6.0.1 on 2026-04-30 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_product_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='moderated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
