# Generated by Django 6.0.1 on 2026-05-01 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_product_moderated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='food_groups',
            field=models.CharField(choices=[('MT', 'Meat'), ('DA', 'Dairy'), ('EG', 'Eggs'), ('FR', 'Fruit'), ('VEG', 'Vegetables'), ('BAK', 'Bakery'), ('PRE', 'Preserves & Jams'), ('PIC', 'Pickled & Fermented'), ('SWT', 'Honey & Syrups'), ('BEV', 'Juices & Beverages'), ('SNK', 'Snacks & Confectionery'), ('ART', 'Artisan Goods')], default='VEG', max_length=20),
        ),
    ]
