# Generated by Django 6.0.1 on 2026-05-02 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_inventory_status'),
        ('products', '0017_alter_category_food_groups'),
    ]

    operations = [
    ]
