# Generated by Django 6.0.1 on 2026-05-05 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_product_is_seasonal_product_season_end_and_more'),
        ('products', '0018_merge_20260502_2302'),
    ]

    operations = [
    ]
